"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import toast, { Toaster } from "react-hot-toast"; 
import Link from "next/link";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  // console.log(pathname);
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [loggedIn, setLoggedIn] = useState(false);

  const checkAuth = () => {
    const isLoggedIn = localStorage.getItem("isLoggedIn");
    const storedUser = localStorage.getItem("username");

    if (isLoggedIn) {
      setLoggedIn(true);
      setUsername(storedUser || "");
    } else {
      setLoggedIn(false);
      if (pathname !== "/") router.push("/");
    }
  };

  useEffect(() => {
    checkAuth();
    window.addEventListener("storage", checkAuth);
    return () => window.removeEventListener("storage", checkAuth);
  }, [router]);

  const handleLogout = () => {
    localStorage.removeItem("isLoggedIn");
    localStorage.removeItem("username");
    setLoggedIn(false);
    window.dispatchEvent(new Event("storage")); // notify all listeners
    toast.success("Logout Successfully.");
    router.push("/");
  }
  return (
    <html lang="en">
      <head>
       {/* Google tag (gtag.js) */}
       <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-66W3Z6YZVE"
          strategy="afterInteractive"
        />
        <Script id="ga-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){window.dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-66W3Z6YZVE');
          `}
        </Script>

      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <section className={'container'}>
        <div className="flex justify-between">
          <ul>
              {!loggedIn ? (<li><Link href="/">Login</Link></li>) : ''}
              <li><Link href="/about" data-active={pathname === '/about'}>About</Link></li>
              <li><Link href="/services/csr">Services</Link></li>
              <li><Link href="/contacts" data-active={pathname === '/contacts'}>Contact</Link></li>
          </ul>
      
          {loggedIn ? (
              <ul>
                <li><h1 className="text-xl font-bold mr-2">Welcome, {username}</h1></li>
                <li>
                  <button onClick={handleLogout} className="px-4 py-1 bg-red-500 text-white rounded-md cursor-pointer hover:bg-red-600">
                    Logout
                  </button>
                </li>
              </ul>
          ) : null}
        </div>
      </section>
        {children}
        <section className={'container'}>
          <div className="bg-gray-500 text-center text-white p-3">
            Footer
          </div>
        </section>
        <Toaster position="top-right" reverseOrder={false}
         toastOptions={{
            duration: 5000, // 6 seconds for all toasts
            style: {
              minWidth: "400px",
              padding: "16px",
            },
          }}
         />
      </body>
    </html>
  );
}
